# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.21.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.21.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sonyjain/Desktop/diyaa2-sonyj9-khushig3-rushika2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sonyjain/Desktop/diyaa2-sonyj9-khushig3-rushika2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.21.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.21.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sonyjain/Desktop/diyaa2-sonyj9-khushig3-rushika2/CMakeFiles /Users/sonyjain/Desktop/diyaa2-sonyj9-khushig3-rushika2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sonyjain/Desktop/diyaa2-sonyj9-khushig3-rushika2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test-functions

# Build rule for target.
test-functions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-functions
.PHONY : test-functions

# fast build rule for target.
test-functions/fast:
	$(MAKE) $(MAKESILENT) -f functions/CMakeFiles/test-functions.dir/build.make functions/CMakeFiles/test-functions.dir/build
.PHONY : test-functions/fast

#=============================================================================
# Target rules for targets named main-functions

# Build rule for target.
main-functions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-functions
.PHONY : main-functions

# fast build rule for target.
main-functions/fast:
	$(MAKE) $(MAKESILENT) -f functions/CMakeFiles/main-functions.dir/build.make functions/CMakeFiles/main-functions.dir/build
.PHONY : main-functions/fast

#=============================================================================
# Target rules for targets named FunctionsLib

# Build rule for target.
FunctionsLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FunctionsLib
.PHONY : FunctionsLib

# fast build rule for target.
FunctionsLib/fast:
	$(MAKE) $(MAKESILENT) -f functions/CMakeFiles/FunctionsLib.dir/build.make functions/CMakeFiles/FunctionsLib.dir/build
.PHONY : FunctionsLib/fast

#=============================================================================
# Target rules for targets named test-person

# Build rule for target.
test-person: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-person
.PHONY : test-person

# fast build rule for target.
test-person/fast:
	$(MAKE) $(MAKESILENT) -f Person/CMakeFiles/test-person.dir/build.make Person/CMakeFiles/test-person.dir/build
.PHONY : test-person/fast

#=============================================================================
# Target rules for targets named main-person

# Build rule for target.
main-person: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-person
.PHONY : main-person

# fast build rule for target.
main-person/fast:
	$(MAKE) $(MAKESILENT) -f Person/CMakeFiles/main-person.dir/build.make Person/CMakeFiles/main-person.dir/build
.PHONY : main-person/fast

#=============================================================================
# Target rules for targets named PersonLib

# Build rule for target.
PersonLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PersonLib
.PHONY : PersonLib

# fast build rule for target.
PersonLib/fast:
	$(MAKE) $(MAKESILENT) -f Person/CMakeFiles/PersonLib.dir/build.make Person/CMakeFiles/PersonLib.dir/build
.PHONY : PersonLib/fast

#=============================================================================
# Target rules for targets named test-network

# Build rule for target.
test-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-network
.PHONY : test-network

# fast build rule for target.
test-network/fast:
	$(MAKE) $(MAKESILENT) -f Network/CMakeFiles/test-network.dir/build.make Network/CMakeFiles/test-network.dir/build
.PHONY : test-network/fast

#=============================================================================
# Target rules for targets named main-network

# Build rule for target.
main-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-network
.PHONY : main-network

# fast build rule for target.
main-network/fast:
	$(MAKE) $(MAKESILENT) -f Network/CMakeFiles/main-network.dir/build.make Network/CMakeFiles/main-network.dir/build
.PHONY : main-network/fast

#=============================================================================
# Target rules for targets named NetworkLib

# Build rule for target.
NetworkLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NetworkLib
.PHONY : NetworkLib

# fast build rule for target.
NetworkLib/fast:
	$(MAKE) $(MAKESILENT) -f Network/CMakeFiles/NetworkLib.dir/build.make Network/CMakeFiles/NetworkLib.dir/build
.PHONY : NetworkLib/fast

#=============================================================================
# Target rules for targets named test-traversal

# Build rule for target.
test-traversal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-traversal
.PHONY : test-traversal

# fast build rule for target.
test-traversal/fast:
	$(MAKE) $(MAKESILENT) -f graphTraversal/CMakeFiles/test-traversal.dir/build.make graphTraversal/CMakeFiles/test-traversal.dir/build
.PHONY : test-traversal/fast

#=============================================================================
# Target rules for targets named main-traversal

# Build rule for target.
main-traversal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-traversal
.PHONY : main-traversal

# fast build rule for target.
main-traversal/fast:
	$(MAKE) $(MAKESILENT) -f graphTraversal/CMakeFiles/main-traversal.dir/build.make graphTraversal/CMakeFiles/main-traversal.dir/build
.PHONY : main-traversal/fast

#=============================================================================
# Target rules for targets named TraversalLib

# Build rule for target.
TraversalLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TraversalLib
.PHONY : TraversalLib

# fast build rule for target.
TraversalLib/fast:
	$(MAKE) $(MAKESILENT) -f graphTraversal/CMakeFiles/TraversalLib.dir/build.make graphTraversal/CMakeFiles/TraversalLib.dir/build
.PHONY : TraversalLib/fast

#=============================================================================
# Target rules for targets named main-dsets

# Build rule for target.
main-dsets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-dsets
.PHONY : main-dsets

# fast build rule for target.
main-dsets/fast:
	$(MAKE) $(MAKESILENT) -f DSets/CMakeFiles/main-dsets.dir/build.make DSets/CMakeFiles/main-dsets.dir/build
.PHONY : main-dsets/fast

#=============================================================================
# Target rules for targets named test-dsets

# Build rule for target.
test-dsets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-dsets
.PHONY : test-dsets

# fast build rule for target.
test-dsets/fast:
	$(MAKE) $(MAKESILENT) -f DSets/CMakeFiles/test-dsets.dir/build.make DSets/CMakeFiles/test-dsets.dir/build
.PHONY : test-dsets/fast

#=============================================================================
# Target rules for targets named DSetsLib

# Build rule for target.
DSetsLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DSetsLib
.PHONY : DSetsLib

# fast build rule for target.
DSetsLib/fast:
	$(MAKE) $(MAKESILENT) -f DSets/CMakeFiles/DSetsLib.dir/build.make DSets/CMakeFiles/DSetsLib.dir/build
.PHONY : DSetsLib/fast

#=============================================================================
# Target rules for targets named test-project

# Build rule for target.
test-project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-project
.PHONY : test-project

# fast build rule for target.
test-project/fast:
	$(MAKE) $(MAKESILENT) -f Project/CMakeFiles/test-project.dir/build.make Project/CMakeFiles/test-project.dir/build
.PHONY : test-project/fast

#=============================================================================
# Target rules for targets named main-project

# Build rule for target.
main-project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-project
.PHONY : main-project

# fast build rule for target.
main-project/fast:
	$(MAKE) $(MAKESILENT) -f Project/CMakeFiles/main-project.dir/build.make Project/CMakeFiles/main-project.dir/build
.PHONY : main-project/fast

#=============================================================================
# Target rules for targets named ProjectLib

# Build rule for target.
ProjectLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProjectLib
.PHONY : ProjectLib

# fast build rule for target.
ProjectLib/fast:
	$(MAKE) $(MAKESILENT) -f Project/CMakeFiles/ProjectLib.dir/build.make Project/CMakeFiles/ProjectLib.dir/build
.PHONY : ProjectLib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DSetsLib"
	@echo "... FunctionsLib"
	@echo "... NetworkLib"
	@echo "... PersonLib"
	@echo "... ProjectLib"
	@echo "... TraversalLib"
	@echo "... main-dsets"
	@echo "... main-functions"
	@echo "... main-network"
	@echo "... main-person"
	@echo "... main-project"
	@echo "... main-traversal"
	@echo "... test-dsets"
	@echo "... test-functions"
	@echo "... test-network"
	@echo "... test-person"
	@echo "... test-project"
	@echo "... test-traversal"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

